export const CLOSE_MODAL = "CLOSE_MODAL";
export const SHOW_COMMENTS_FORM = "SHOW_COMMENTS_FORM";

export const ARTISTS_FETCH_REQUEST = "ARTISTS_FETCH_REQUEST";
export const ARTISTS_FETCH_SUCCESS = "ARTISTS_FETCH_SUCCESS";
export const ARTISTS_FETCH_FAILURE = "ARTISTS_FETCH_FAILURE";

export const ARTIST_FETCH_REQUEST = "ARTIST_FETCH_REQUEST";
export const ARTIST_FETCH_SUCCESS = "ARTIST_FETCH_SUCCESS";
export const ARTIST_FETCH_FAILURE = "ARTIST_FETCH_FAILURE";

export const ARTIST_TRACKS_FETCH_REQUEST = "ARTIST_TRACKS_FETCH_REQUEST";
export const ARTIST_TRACKS_FETCH_SUCCESS = "ARTIST_TRACKS_FETCH_SUCCESS";
export const ARTIST_TRACKS_FETCH_FAILURE = "ARTIST_TRACKS_FETCH_FAILURE";

export const ARTIST_ALBUMS_FETCH_REQUEST = "ARTIST_ALBUMS_FETCH_REQUEST";
export const ARTIST_ALBUMS_FETCH_SUCCESS = "ARTIST_ALBUMS_FETCH_SUCCESS";
export const ARTIST_ALBUMS_FETCH_FAILURE = "ARTIST_ALBUMS_FETCH_FAILURE";

export const ALBUMS_FETCH_REQUEST = "ALBUMS_FETCH_REQUEST";
export const ALBUMS_FETCH_SUCCESS = "ALBUMS_FETCH_SUCCESS";
export const ALBUMS_FETCH_FAILURE = "ALBUMS_FETCH_FAILURE";

export const ALBUM_FETCH_REQUEST = "ALBUM_FETCH_REQUEST";
export const ALBUM_FETCH_SUCCESS = "ALBUM_FETCH_SUCCESS";
export const ALBUM_FETCH_FAILURE = "ALBUM_FETCH_FAILURE";

export const ALBUM_TRACKS_FETCH_REQUEST = "ALBUM_TRACKS_FETCH_REQUEST";
export const ALBUM_TRACKS_FETCH_SUCCESS = "ALBUM_TRACKS_FETCH_SUCCESS";
export const ALBUM_TRACKS_FETCH_FAILURE = "ALBUM_TRACKS_FETCH_FAILURE";
